---
galaxy_info:
  role_name: technitium
  namespace: khaosx
  author: Kris
  description: Install and manage Technitium DNS Server on Ubuntu with optional TLS automation.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
  galaxy_tags:
    - dns
    - technitium
    - ubuntu
    - tls

dependencies: []
